#
spring:
  application:
    name: HB-INSURE-APP-API
server:
  port: 9001
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    registry-fetch-interval-seconds: 5
#
ribbon:
  #eureka客户端ribbon刷新时间（）
  ServerListRefreshInterval: 1000
  #全局设置-请求超7s后超时-默认5s
  ReadTimeout: 7000
  #连接超10s后超时-默认2s
  ConnectTimeout: 10000
  #同一实例重试策略=尝试0次
  MaxAutoRetries: 0
  #失败0次之后才更换实例访问=失败后但不更换实例
  MaxAutoRetriesNextServer: 1
  #重试任何操作都不进行重试
  #OkToRetryOnAllOperations: false 代表只有get模式才进行重试-post模式重试会出现脏数据-幂等问题
  OkToRetryOnAllOperations: false
  eureka:
    enabled: true
#
feign:
  hystrix:
    #开启熔断保护
    enabled: true
#关闭hystrix的执行超时功能，这样只设置ribbon的超时就可以
hystrix.command.default.execution.timeout.enabled: false
#设置APP接口的统一版本，用于重大的功能升级使用-此配置暂定（2018-09-15-1732）
app.version: v1
##