#
spring:
  application:
    name: HB-INSURE-APP-API
server:
  port: 9001
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#
ribbon:
  eureka:
    enabled: true