#
spring:
  application:
    name: HB-ORDER-SERVICE-PROVIDER
  profiles:
    active: dev
    #指定抽样比例
  sleuth.sampler.probability: 1.0
    #指定zipkin中心
  zipkin.base-url: http://localhost:9411
server:
  port: 9000
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
#调试验证重试策略-打印访问路径--主要用于测试
logging.level.org.springframework.web.servlet.DispatcherServlet: debug
#logback path
logging.config: classpath:logback-spring.xml