spring:
  application:
    name: HB_EUREKA_SERVER
eureka:
  environment: dev
---
server:
  port: 8761
spring:
  # 指定profile=peer1
  profiles: peer1
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
    #preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      #不要向注册中心注册自己
      #register-with-eureka: false
      #禁止检索服务
      #fetch-registry: false
      # 将自己注册到peer2、peer3这个Eureka上面去
      defaultZone: http://peer2:8762/eureka/
  server:
    #过期实例应该启动并运行的时间间隔，单位为毫秒，默认为60 * 1000
    eviction-interval-timer-in-ms: 4000
    #打开保护机制
    enable-self-preservation: true
    #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    waitTimeInMsWhenSyncEmpty: 0
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    #preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
  server:
    #过期实例应该启动并运行的时间间隔，单位为毫秒，默认为60 * 1000
    eviction-interval-timer-in-ms: 4000
    #打开保护机制
    enable-self-preservation: true
    #在Eureka服务器获取不到集群里对等服务器上的实例时，需要等待的时间，单位为毫秒，默认为1000 * 60 * 5
    waitTimeInMsWhenSyncEmpty: 0